import type { PluginSurfaceProps } from "@getpaseo/plugin/client";
import { useMemo } from "react";
import { StyleSheet } from "react-native";

export function useBoardStyles(theme: PluginSurfaceProps["theme"], compact: boolean) {
  return useMemo(
    () =>
      StyleSheet.create({
        screen: {
          flex: 1,
          backgroundColor: theme.colors.surface0,
          padding: compact ? 10 : 16,
          gap: 10,
        },
        header: {
          flexDirection: "row",
          flexWrap: "wrap",
          alignItems: "center",
          gap: 10,
        },
        toolbar: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 7 },
        controlBar: {
          flexDirection: "row",
          flexWrap: "wrap",
          alignItems: "center",
          gap: 7,
          padding: 7,
          borderWidth: 1,
          borderColor: theme.colors.border,
          borderRadius: 0,
          backgroundColor: theme.colors.surface1,
        },
        heading: {
          color: theme.colors.foreground,
          fontSize: compact ? 21 : 26,
          fontWeight: "800",
          letterSpacing: -0.4,
        },
        text: { color: theme.colors.foreground, fontSize: 14 },
        muted: { color: theme.colors.foregroundMuted, fontSize: 12 },
        input: {
          minHeight: 36,
          minWidth: 180,
          flexGrow: 1,
          color: theme.colors.foreground,
          backgroundColor: theme.colors.surface0,
          borderColor: theme.colors.border,
          borderWidth: 1,
          borderRadius: 0,
          paddingHorizontal: 10,
          paddingVertical: 7,
        },
        descriptionInput: { minHeight: 96, textAlignVertical: "top" },
        button: {
          minHeight: 34,
          justifyContent: "center",
          paddingHorizontal: 10,
          paddingVertical: 6,
          borderRadius: 0,
          backgroundColor: theme.colors.surface2,
          borderColor: theme.colors.border,
          borderWidth: 1,
        },
        primaryButton: { backgroundColor: theme.colors.accent, borderColor: theme.colors.accent },
        dangerButton: { borderColor: theme.colors.statusDanger },
        buttonText: { color: theme.colors.foreground, fontSize: 13, fontWeight: "600" },
        primaryButtonText: { color: theme.colors.accentForeground },
        dangerButtonText: { color: theme.colors.statusDanger },
        chip: {
          paddingHorizontal: 10,
          paddingVertical: 7,
          borderRadius: 0,
          borderColor: theme.colors.border,
          borderWidth: 1,
          backgroundColor: theme.colors.surface0,
        },
        selectedChip: { backgroundColor: theme.colors.accent, borderColor: theme.colors.accent },
        selectedChipText: { color: theme.colors.accentForeground },
        projectButton: {
          minHeight: 36,
          maxWidth: compact ? "100%" : 420,
          flexGrow: compact ? 1 : 0,
          flexShrink: 1,
          flexDirection: "row",
          alignItems: "center",
          gap: 8,
          paddingHorizontal: 10,
          borderWidth: 1,
          borderColor: theme.colors.border,
          backgroundColor: theme.colors.surface1,
        },
        projectButtonLabel: {
          color: theme.colors.foregroundMuted,
          fontSize: 10,
          fontWeight: "800",
          letterSpacing: 0.8,
        },
        projectButtonText: {
          flexShrink: 1,
          color: theme.colors.foreground,
          fontSize: 13,
          fontWeight: "700",
        },
        projectButtonChevron: {
          marginLeft: "auto",
          color: theme.colors.foregroundMuted,
          fontSize: 12,
        },
        projectPicker: {
          maxHeight: 280,
          gap: 8,
          padding: 8,
          borderWidth: 1,
          borderColor: theme.colors.border,
          backgroundColor: theme.colors.surface1,
        },
        projectList: { maxHeight: 220 },
        projectOptions: { gap: 1 },
        projectOption: {
          minHeight: 36,
          justifyContent: "center",
          paddingHorizontal: 10,
          paddingVertical: 7,
          borderLeftWidth: 3,
          borderLeftColor: "transparent",
          backgroundColor: theme.colors.surface0,
        },
        selectedProjectOption: {
          borderLeftColor: theme.colors.accent,
          backgroundColor: theme.colors.surface2,
        },
        projectOptionText: { color: theme.colors.foreground, fontSize: 13, fontWeight: "600" },
        panel: {
          gap: 10,
          padding: 12,
          borderRadius: 0,
          borderWidth: 1,
          borderLeftWidth: 3,
          borderColor: theme.colors.border,
          borderLeftColor: theme.colors.accent,
          backgroundColor: theme.colors.surface1,
        },
        board: {
          flexGrow: 1,
          flexDirection: compact ? "column" : "row",
          alignItems: "stretch",
          gap: 10,
          paddingBottom: 12,
        },
        column: {
          width: compact ? "100%" : 286,
          minHeight: compact ? 120 : 420,
          padding: 10,
          gap: 10,
          borderRadius: 0,
          backgroundColor: theme.colors.surface1,
          borderWidth: 1,
          borderTopWidth: 3,
          borderColor: theme.colors.border,
        },
        columnHeader: {
          flexDirection: "row",
          justifyContent: "space-between",
          alignItems: "center",
          paddingBottom: 8,
          borderBottomWidth: 1,
          borderBottomColor: theme.colors.border,
        },
        columnTitle: {
          color: theme.colors.foreground,
          fontSize: 13,
          fontWeight: "800",
          letterSpacing: 0.2,
        },
        count: {
          minWidth: 22,
          color: theme.colors.foregroundMuted,
          backgroundColor: theme.colors.surface2,
          borderRadius: 0,
          paddingHorizontal: 6,
          paddingVertical: 2,
          fontSize: 11,
          fontWeight: "700",
          textAlign: "center",
        },
        card: {
          padding: 10,
          gap: 7,
          borderRadius: 0,
          backgroundColor: theme.colors.surface0,
          borderWidth: 1,
          borderLeftWidth: 3,
          borderColor: theme.colors.border,
        },
        cardKey: { color: theme.colors.accent, fontSize: 10, fontWeight: "800", letterSpacing: 0.6 },
        cardTitle: { color: theme.colors.foreground, fontSize: 14, fontWeight: "700", lineHeight: 19 },
        cardActions: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
        badge: { alignSelf: "flex-start", borderRadius: 0, paddingHorizontal: 7, paddingVertical: 3 },
        badgeText: { color: theme.colors.accentForeground, fontSize: 10, fontWeight: "800" },
        error: { color: theme.colors.statusDanger, fontSize: 13 },
        warning: { color: theme.colors.statusWarning, fontSize: 13 },
        success: { color: theme.colors.statusSuccess, fontSize: 13 },
        sectionLabel: {
          color: theme.colors.foregroundMuted,
          fontSize: 10,
          fontWeight: "800",
          letterSpacing: 0.8,
        },
      }),
    [compact, theme],
  );
}

export type BoardStyles = ReturnType<(typeof useBoardStyles)>;
